### ISSUE TITLE
少し見にくいので設定画面を改善して欲しい

### ISSUE THREAD

**Issue by arigayas** [nekoziroo/Niconico-Downloader#3]
### ファイル名
○タイトル
○動画ID
○タイトルと動画ID _プルリクがあったので追加しました_ 

### 保存先のフォルダ
□「名前を付けて保存」を表示 (ポップアップで「チェックを入れると保存フォルダを選択可能です」のような説明が欲しいです)

使用環境：Windows10+Firefox Developer Edition

**Comment by nekoziroo** [comment]
こんな感じでしょうか。
ポップアップはcssが苦手なので難しいです。
![3](https://user-images.githubusercontent.com/26833179/45035775-c49c6680-b095-11e8-9681-753152914f7d.PNG)

**Comment by arigayas** [comment]
対応していただきありがとうございます。

チェックボックスやラジオボタンが行頭にあるとマウスを上下させるだけで良いと思うのですが、
技術的に難しいのでしょうか？

アドオンの作成方法については全く知りませんが、
ポップアップは正しい言葉ではなくてツールチップのことでした。
Title属性を使うと表示されるかもしれません。

**Comment by nekoziroo** [comment]
できました。
![3-2](https://user-images.githubusercontent.com/26833179/45037869-f6fc9280-b09a-11e8-9432-d9dfbb46e796.png)

**Comment by arigayas** [comment]
おお！速い！！
